### ISSUE TITLE
闭括号会被换行？

### ISSUE THREAD

**Issue by TingYa** [drakeet/LayoutFormatter#1]
难道是我的姿势不对？
![](http://ww1.sinaimg.cn/large/7bdcf253gw1f2t4d2xr57j20yw0e0aeh.jpg)

**Comment by Piasy** [comment]
建议是回括号换行吧？更利于（在最后一行后面）新加一个attr。

**Comment by drakeet** [comment]
已经在最新版中修复这个问题了。
