### ISSUE TITLE
有没有考虑做一个抽取 xml 属性 到 style 文件的插件

### ISSUE THREAD

**Issue by maoruibin** [drakeet/LayoutFormatter#11]
有没有考虑做一个抽取 xml 属性 到 style 文件的插件？
具体场景 
选中一段 xml  属性文件，在 style.xml 文件生成对应的 style !

**Comment by drakeet** [comment]
有的 ^_^ todo...
咕咚 <notifications@github.com>于2016年5月20日 周五19:11写道：

**Comment by maoruibin** [comment]
wa o ~ 
I like you 「todo」

**Comment by drakeet** [comment]
咦！我看错了，你需求的这个功能 AS 本来就有...我以为你指的是 XML 配置 rules
咕咚 <notifications@github.com>于2016年5月20日 周五23:37写道：

**Comment by maoruibin** [comment]
是吗？我怎么不知道呀~ 怎么操作来着 ！！！ 求指导

**Comment by drakeet** [comment]
![](http://ww2.sinaimg.cn/large/86e2ff85gw1f42a2ihjinj21fu0wc13h.jpg)

**Comment by maoruibin** [comment]
哇偶 ~ 真是啊 ！ 嘎嘎嘎 ~ 新技能 get 最近在写布局一大堆的属性要迁移到 style 统一管理 瞬间得救了 ，thanks ~

via CloudMagic for Mac [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.6.18&pv=10.11.4&source=email_footer_2]
On Fri, May 20, 2016 at 11:41 PM, drakeet <notifications@github.com> wrote:
[https://camo.githubusercontent.com/6d51d3b2ddd5e1d7fda7a78507f548b911c4abd4/687474703a2f2f7777322e73696e61696d672e636e2f6c617267652f3836653266663835677731663432613269686a696e6a323166753077633133682e6a7067]
