### ISSUE TITLE
The fact that this project is deprecated is not visible enough

### ISSUE THREAD

**Issue by LouisCAD** [drakeet/LayoutFormatter#12]
Hi!
The short project description and the first line of the readme should both have this as their first word: "Deprecated", instead of being at the end of the readme, in a not so big font size.

I say this because someone tweeted about this library today, thinking it offered something not bundled in Android Studio.

**Comment by drakeet** [comment]
Thanks for your reminder, but I have already explained: 

![image](https://cloud.githubusercontent.com/assets/5214214/17643705/7a9be16a-61a4-11e6-94b2-f33208923191.png)
