### ISSUE TITLE
android:singleLine="true"(It's deprecated) -> android:maxLines="1";

### ISSUE THREAD

**Issue by hejinalex** [drakeet/LayoutFormatter#13]
做TextView滚动效果(跑马灯)的时候，android:singleLine="true"可行，android:maxLines="1";不可行。
所以将android:singleLine="true"自动转为android:maxLines="1"不太妥。

**Comment by drakeet** [comment]
你说的不错，我也发现了，晚上回去撤回这个替换。顺便吐槽一句：妈蛋，Android 官方真坑！

**Comment by hejinalex** [comment]
AS也提示的这样修改，官方真心不靠谱啊。

**Comment by drakeet** [comment]
是的，把旧的废弃掉了，建议了新的，结果新的并不能完全替代旧的，不靠谱。

**Comment by drakeet** [comment]
已更新修复：https://plugins.jetbrains.com/plugin/8299

**Comment by Arlene614** [comment]
加一个设置 android:inputType="text",就好了，
