### ISSUE TITLE
 AssertionError: Wrong line separators: '...al_margin\"\r\n>\n\n    <...' 

### ISSUE THREAD

**Issue by TonyZZX** [drakeet/LayoutFormatter#3]
22:43:23 Plugin Error: LayoutFormatter threw an uncaught AssertionError. Disable Plugin
22:43:23 AssertionError: Wrong line separators: '...al_margin\"\r\n>\n\n    <...' at offset 281

**Comment by OtzOrz** [comment]
I meet it ,But  I  don't konew why...
