### ISSUE TITLE
在Android Studio 2.0上无法使用

### ISSUE THREAD

**Issue by ltd920678778** [drakeet/LayoutFormatter#4]
Android Studio 2.0 ,  LayoutFormatter 1.04. 
无法使用, 报错信息如下(重复4次): 
14:39:21 AssertionError: Wrong line separators: '...iveLayout>\r\n' at offset 10846
14:39:38 AssertionError: Wrong line separators: '...iveLayout>\r\n' at offset 10846
14:40:13 AssertionError: Wrong line separators: '...set 10846\n\r\n' at offset 653
14:43:11 AssertionError: Wrong line separators: '...ffset 653\n\r\n' at offset 824

难道是我自己写的XML文件不合乎规范么,?

**Comment by drakeet** [comment]
我的可以，你的电脑是 Mac OSX 还是 Windows？

**Comment by ltd920678778** [comment]
你好：
我工作用的是windows，那我下班回去后用在Mac上试试.
谢谢回复！


2016年4月20日 +0800 16:00 drakeet <notifications@github.com>，写道：

我的可以，你的电脑是 Mac OSX 还是 Windows？

**Comment by wangdd1201** [comment]
我的电脑是windows的不行，formatter都没有

**Comment by fishwjy** [comment]
windows下enter是 \n\r,unix下是\n,mac下是\r，所以是不是这里出错了？

**Comment by ltd920678778** [comment]
我在Mac上试了是可以的！


2016年4月21日 +0800 10:52 Vincent <notifications@github.com>，写道：

windows下enter是 \n\r,unix下是\n,mac下是\r，所以是不是这里出错了？

**Comment by Muyiafan** [comment]
#10 Windows下，**Document类** 使用 **\n** 来处理换行。直接使用 **File类** 读取文件倒是会有 **\n\r** 的问题。
