### ISSUE TITLE
eclipse可以用吗

### ISSUE THREAD

**Issue by Coder-DanielHan** [drakeet/LayoutFormatter#5]
eclipse可以用吗

**Comment by drakeet** [comment]
![](https://camo.githubusercontent.com/bd9052cb8a5713d0ff354dfb8ab52dacdfd057c4/687474703a2f2f7777342e73696e61696d672e636e2f6c617267652f3565396138316462677731657539306d30387638366a323064773039613379752e6a7067)

（开个玩笑。eclipse 不支持，还是感激换 AS 吧）
